version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - queue

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hooprank
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  queue:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
