import '../models.dart';

final List<Player> mockPlayers = [
  Player(
    id: '1',
    slug: 'aja-wilson',
    name: "A'ja Wilson",
    team: 'Aces',
    position: 'F',
    age: 28,
    height: '6\'4"',
    weight: '195 lb',
    zip: '89101',
    rating: 4.9,
    offense: 4.7,
    defense: 5.0,
    shooting: 4.6,
    passing: 4.0,
    rebounding: 5.0,
  ),
  Player(
    id: '2',
    slug: 'breanna-stewart',
    name: 'Breanna Stewart',
    team: 'Liberty',
    position: 'F',
    age: 31,
    height: '6\'4"',
    weight: '170 lb',
    zip: '10001',
    rating: 4.7,
    offense: 4.6,
    defense: 4.9,
    shooting: 4.6,
    passing: 4.3,
    rebounding: 4.7,
  ),
  Player(
    id: '3',
    slug: 'sabrina-ionescu',
    name: 'Sabrina Ionescu',
    team: 'Liberty',
    position: 'G',
    age: 27,
    height: '5\'11"',
    weight: '165 lb',
    zip: '10001',
    rating: 4.6,
    offense: 4.7,
    defense: 4.0,
    shooting: 4.8,
    passing: 4.6,
    rebounding: 3.6,
  ),
  Player(
    id: '4',
    slug: 'alyssa-thomas',
    name: 'Alyssa Thomas',
    team: 'Sun',
    position: 'F',
    age: 32,
    height: '6\'2"',
    weight: '185 lb',
    zip: '06103',
    rating: 4.5,
    offense: 4.3,
    defense: 4.9,
    shooting: 4.1,
    passing: 4.7,
    rebounding: 4.6,
  ),
  Player(
    id: '5',
    slug: 'caitlin-clark',
    name: 'Caitlin Clark',
    team: 'Fever',
    position: 'G',
    age: 23,
    height: '6\'0"',
    weight: '155 lb',
    zip: '46204',
    rating: 4.3,
    offense: 4.6,
    defense: 3.5,
    shooting: 4.9,
    passing: 4.6,
    rebounding: 3.1,
  ),
  Player(
    id: '6',
    slug: 'aliyah-boston',
    name: 'Aliyah Boston',
    team: 'Fever',
    position: 'C',
    age: 23,
    height: '6\'5"',
    weight: '220 lb',
    zip: '46204',
    rating: 4.3,
    offense: 4.1,
    defense: 4.6,
    shooting: 4.1,
    passing: 3.8,
    rebounding: 4.8,
  ),
  Player(
    id: '7',
    slug: 'kelsey-plum',
    name: 'Kelsey Plum',
    team: 'Aces',
    position: 'G',
    age: 30,
    height: '5\'8"',
    weight: '145 lb',
    zip: '89101',
    rating: 4.4,
    offense: 4.6,
    defense: 3.6,
    shooting: 4.7,
    passing: 4.3,
    rebounding: 2.8,
  ),
  Player(
    id: '8',
    slug: 'ariel-atkins',
    name: 'Ariel Atkins',
    team: 'Mystics',
    position: 'G',
    age: 28,
    height: '5\'10"',
    weight: '167 lb',
    zip: '20001',
    rating: 4.0,
    offense: 4.0,
    defense: 4.5,
    shooting: 4.3,
    passing: 4.0,
    rebounding: 3.0,
  ),
];

final List<Match> mockMatches = [
  Match(
    id: 'm1',
    challengerId: '1',
    opponentId: '2',
    status: 'pending',
    scheduledAt: DateTime.now().add(const Duration(days: 1)),
    courtId: 'court_1',
  ),
  Match(
    id: 'm2',
    challengerId: '3',
    opponentId: '4',
    status: 'accepted',
    scheduledAt: DateTime.now().add(const Duration(days: 2)),
    courtId: 'court_2',
  ),
  Match(
    id: 'm3',
    challengerId: '5',
    opponentId: '7',
    status: 'completed',
    scheduledAt: DateTime.now().subtract(const Duration(days: 1)),
    courtId: 'court_3',
    winnerId: '5',
    ratingDelta: 0.12,
  ),
];
