name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Unit tests
        run: npm test
        working-directory: backend

      - name: Docker Compose up (backend + deps)
        run: |
          docker compose version
          docker compose up -d --build backend db redis queue
          echo "Waiting for backend on :3000..."
          for i in {1..90}; do
            if curl -sf http://localhost:3000/health >/dev/null; then
              echo "Backend is up"; break
            fi
            sleep 1
          done
          curl -sSf http://localhost:3000/health

      - name: Version endpoint
        run: curl -sSf http://localhost:3000/api/v1/version || true

      - name: Docker Compose down
        if: always()
        run: docker compose down -v
