name: Release Backend Image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2
      ECR_REPO: hooprank-backend
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/github-oidc-hooprank
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}"
          TAG="${GITHUB_REF_NAME}"
          docker build -t "$IMAGE:$TAG" backend
          docker tag "$IMAGE:$TAG" "$IMAGE:latest"
          echo "IMAGE_URI=$IMAGE:$TAG" >> $GITHUB_ENV

      - name: Push image
        run: |
          docker push "${IMAGE_URI}"
          docker push "${IMAGE_URI%:*}:latest"
